### ISSUE TITLE
Project TODO List

### ISSUE THREAD

**Issue by leocast** [leocast/historic-weather-calendar-app#1]
# Birthday Weather History App
## Overview:

User fills out form with their Birthday Date and the County and State in which they were born.
Server takes the User's data and queries NOAA's Historic Observing Metadata Repository for...
- The weather station's ID for that County/State
- All Weather data for that weather station since the user's birthday, to be parsed by the application

NOAA returns the data in JSON
Use javascript to 
- Parse the JSON returned from NOAA to get high temperature for the user's birthday, starting from their birth year
- Use a JavaScript or jQuery graph program (or D3) to plot the temperature points fro each year, plus the mean as a line running through the points.
## URLs
- [ ] get historic weather data in JSON from https://www.ncdc.noaa.gov/homr/api
- [ ] Use D3 or other JavaScript based graphing tool to dynamically display the data
  - [ ] http://c3js.org/ (makes using D3 library easier)
  - [ ] https://github.com/d3/d3
